//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSRS.WebAPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSRS_IS_MAIN
    {
        public int ID { get; set; }
        public Nullable<int> SSRS_CLASSIFICATION_TABLE_TYPE_ID { get; set; }
        public Nullable<int> SSRS_ATTRIBUTE_ID { get; set; }
        public string PRIORITY { get; set; }
    
        public virtual SSRS_ATTRIBUTE SSRS_ATTRIBUTE { get; set; }
        public virtual SSRS_CLASSIFICATION_TABLE_TYPE SSRS_CLASSIFICATION_TABLE_TYPE { get; set; }
    }
}
