//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSRS.WebAPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSRS_CLASSIFICATION_TABLE_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SSRS_CLASSIFICATION_TABLE_TYPE()
        {
            this.SSRS_IS_MAIN = new HashSet<SSRS_IS_MAIN>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SSRS_CLASSIFICATION_TABLE_ID { get; set; }
        public Nullable<int> SSRS_TYPE_ID { get; set; }
        public string DISPLAY_NAME { get; set; }
        public Nullable<int> TABLE_ORDER { get; set; }
    
        public virtual SSRS_CLASSIFICATION_TABLE SSRS_CLASSIFICATION_TABLE { get; set; }
        public virtual SSRS_TYPE SSRS_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSRS_IS_MAIN> SSRS_IS_MAIN { get; set; }
    }
}
