//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSRS.WebAPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSRS_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SSRS_CATEGORY()
        {
            this.SSRS_CLASSIFICATION_CATEGORY = new HashSet<SSRS_CLASSIFICATION_CATEGORY>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> CAT_ORDER { get; set; }
        public Nullable<int> SSRS_MODULE_ID { get; set; }
    
        public virtual SSRS_MODULE SSRS_MODULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSRS_CLASSIFICATION_CATEGORY> SSRS_CLASSIFICATION_CATEGORY { get; set; }
    }
}
