//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSRS.WebAPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSRS_CLASSIFICATION_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SSRS_CLASSIFICATION_TABLE()
        {
            this.SSRS_CLASSIFICATION_TABLE1 = new HashSet<SSRS_CLASSIFICATION_TABLE>();
            this.SSRS_CLASSIFICATION_TABLE_TYPE = new HashSet<SSRS_CLASSIFICATION_TABLE_TYPE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SSRS_CLASSIFICATION_ID { get; set; }
        public Nullable<int> SSRS_TABLE_ID { get; set; }
        public string DISPLAY_NAME { get; set; }
        public Nullable<int> TABLE_ORDER { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public Nullable<int> SSRS_RELATION_TYPE_ID { get; set; }
        public string INJUNCTION_TABLE { get; set; }
    
        public virtual SSRS_CLASSIFICATION SSRS_CLASSIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSRS_CLASSIFICATION_TABLE> SSRS_CLASSIFICATION_TABLE1 { get; set; }
        public virtual SSRS_CLASSIFICATION_TABLE SSRS_CLASSIFICATION_TABLE2 { get; set; }
        public virtual SSRS_TABLE SSRS_TABLE { get; set; }
        public virtual SSRS_RELATION_TYPE SSRS_RELATION_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSRS_CLASSIFICATION_TABLE_TYPE> SSRS_CLASSIFICATION_TABLE_TYPE { get; set; }
    }
}
