//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSRS.WebAPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSRS_CLASSIFICATION_CATEGORY
    {
        public int ID { get; set; }
        public int SSRS_CLASSIFICATION_ID { get; set; }
        public int SSRS_CATEGORY_ID { get; set; }
    
        public virtual SSRS_CATEGORY SSRS_CATEGORY { get; set; }
        public virtual SSRS_CLASSIFICATION SSRS_CLASSIFICATION { get; set; }
    }
}
